//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34011
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PintheCloud.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PintheCloud.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin the Cloud과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GPS doesn&apos;t work well not. Please load it again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadGpsMessage {
            get {
                return ResourceManager.GetString("BadGpsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign In Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadSignInCaption {
            get {
                return ResourceManager.GetString("BadSignInCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign in process met error. Please try it again과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadSignInMessage {
            get {
                return ResourceManager.GetString("BadSignInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    bytes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    GB과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Google Drive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GoogleDrive {
            get {
                return ResourceManager.GetString("GoogleDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interent unavailable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InternetUnavailableCaption {
            get {
                return ResourceManager.GetString("InternetUnavailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorry. Could not connect to At Here. Please check WIFI and try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InternetUnavailableMessage {
            get {
                return ResourceManager.GetString("InternetUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    KB과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///    likes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location Access과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LocationAccess {
            get {
                return ResourceManager.GetString("LocationAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This app accesses your phone&apos;s location. Is that ok?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LocationAccessMessage {
            get {
                return ResourceManager.GetString("LocationAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location Service과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LocationService {
            get {
                return ResourceManager.GetString("LocationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///    MB과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   m과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Spot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MySpot {
            get {
                return ResourceManager.GetString("MySpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no files in your cloud.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoFileInCloudMessage {
            get {
                return ResourceManager.GetString("NoFileInCloudMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gps Off과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoGpsOnCaption {
            get {
                return ResourceManager.GetString("NoGpsOnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location serivces are disabled. Please enable it at your system.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoGpsOnMessage {
            get {
                return ResourceManager.GetString("NoGpsOnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location Acess Consent과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoLocationAcessConsentCaption {
            get {
                return ResourceManager.GetString("NoLocationAcessConsentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This app requires consent to access location information. Please consent it in settings.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoLocationAcessConsentMessage {
            get {
                return ResourceManager.GetString("NoLocationAcessConsentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no your space. Make it yours.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoMySpaceMessage {
            get {
                return ResourceManager.GetString("NoMySpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no near space. Make it yours.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoNearSpaceMessage {
            get {
                return ResourceManager.GetString("NoNearSpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pick과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Pick {
            get {
                return ResourceManager.GetString("Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Private Policy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PrivatePolicy {
            get {
                return ResourceManager.GetString("PrivatePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refreshing...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Refreshing {
            get {
                return ResourceManager.GetString("Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LeftToRight과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en-us과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RootPath {
            get {
                return ResourceManager.GetString("RootPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SignOutCaption {
            get {
                return ResourceManager.GetString("SignOutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want sign out? Your setting will be intialized.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SignOutMessage {
            get {
                return ResourceManager.GetString("SignOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SkyDrive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SkyDrive {
            get {
                return ResourceManager.GetString("SkyDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SkyDrive Sign Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SkyDriveSignOut {
            get {
                return ResourceManager.GetString("SkyDriveSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Terms of Service과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
    }
}
