//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34003
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PintheCloud.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PintheCloud.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin the Cloud과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadLoginCaption {
            get {
                return ResourceManager.GetString("BadLoginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login process stopped. Please try it again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadLoginMessage {
            get {
                return ResourceManager.GetString("BadLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Explorer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Explorer {
            get {
                return ResourceManager.GetString("Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location Access과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LocationAccess {
            get {
                return ResourceManager.GetString("LocationAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This app accesses your phone&apos;s location. Is that ok?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LocationAccessMessage {
            get {
                return ResourceManager.GetString("LocationAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Logout과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want logout? Your setting will be intialized.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Spaces과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MySpaces {
            get {
                return ResourceManager.GetString("MySpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interent unavailable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoInternetCaption {
            get {
                return ResourceManager.GetString("NoInternetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please make sure connection with Internet.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoInternetMessage {
            get {
                return ResourceManager.GetString("NoInternetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no your space. Make it yours.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoMySpaceMessage {
            get {
                return ResourceManager.GetString("NoMySpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no space near from here. Make it yours.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoNearSpaceMessage {
            get {
                return ResourceManager.GetString("NoNearSpaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LeftToRight과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en-us과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please Wait...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
    }
}
