//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34011
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PintheCloud.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PintheCloud.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At Here과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AtHere {
            get {
                return ResourceManager.GetString("AtHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Profile Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadCreateProfileCaption {
            get {
                return ResourceManager.GetString("BadCreateProfileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create profile process met error. Please try it again과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadCreateProfileMessage {
            get {
                return ResourceManager.GetString("BadCreateProfileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete spot process met error. Please try it again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadDeleteSpotMessage {
            get {
                return ResourceManager.GetString("BadDeleteSpotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong Email Address과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadEmailAddressCaption {
            get {
                return ResourceManager.GetString("BadEmailAddressCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please confirm right email address.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadEmailAddressMessage {
            get {
                return ResourceManager.GetString("BadEmailAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading Spot met error. Please try it again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadLoadingSpotMessage {
            get {
                return ResourceManager.GetString("BadLoadingSpotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location Service met error. Please try it again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadLocationServiceMessage {
            get {
                return ResourceManager.GetString("BadLocationServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin spot process met error. Please try it again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadPinSpotMessage {
            get {
                return ResourceManager.GetString("BadPinSpotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign In Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadSignInCaption {
            get {
                return ResourceManager.GetString("BadSignInCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign in process met error. Please try it again과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BadSignInMessage {
            get {
                return ResourceManager.GetString("BadSignInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bytes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CloseAppCaption {
            get {
                return ResourceManager.GetString("CloseAppCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to close At Here?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CloseAppMessage {
            get {
                return ResourceManager.GetString("CloseAppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cloud과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cloud {
            get {
                return ResourceManager.GetString("Cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CloudSignOutCaption {
            get {
                return ResourceManager.GetString("CloudSignOutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want sign out this Cloud? Your setting in this cloud will be intialized.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CloudSignOutMessage {
            get {
                return ResourceManager.GetString("CloudSignOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Creating Profile...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CreateProfile {
            get {
                return ResourceManager.GetString("CreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default Spot Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DefaultSpotName {
            get {
                return ResourceManager.GetString("DefaultSpotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeleteFileCaption {
            get {
                return ResourceManager.GetString("DeleteFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete the selected file?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeleteFileMessage {
            get {
                return ResourceManager.GetString("DeleteFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete My Spot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeleteMySpotCaption {
            get {
                return ResourceManager.GetString("DeleteMySpotCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete the my spot?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DeleteMySpotMessage {
            get {
                return ResourceManager.GetString("DeleteMySpotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doing sign in...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DoingSignIn {
            get {
                return ResourceManager.GetString("DoingSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doing Sign Out...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DoingSignOut {
            get {
                return ResourceManager.GetString("DoingSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dropbox과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Dropbox {
            get {
                return ResourceManager.GetString("Dropbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duplicated Email Address과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DuplicateEmailAddressCaption {
            get {
                return ResourceManager.GetString("DuplicateEmailAddressCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This email address already existed. Please use another email address.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DuplicateEmailAddressMessage {
            get {
                return ResourceManager.GetString("DuplicateEmailAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GB과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Google Doc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GoogleDoc {
            get {
                return ResourceManager.GetString("GoogleDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GoogleDrive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GoogleDrive {
            get {
                return ResourceManager.GetString("GoogleDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interent unavailable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InternetUnavailableCaption {
            get {
                return ResourceManager.GetString("InternetUnavailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not connect to At Here. Please check WIFI and try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string InternetUnavailableMessage {
            get {
                return ResourceManager.GetString("InternetUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KB과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location Access과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LocationAccessCaption {
            get {
                return ResourceManager.GetString("LocationAccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At Here accesses your phone&apos;s location. Is that ok?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LocationAccessMessage {
            get {
                return ResourceManager.GetString("LocationAccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location Service과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LocationService {
            get {
                return ResourceManager.GetString("LocationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Main)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MB과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   m과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Pick과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MyPick {
            get {
                return ResourceManager.GetString("MyPick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   My Spot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MySpot {
            get {
                return ResourceManager.GetString("MySpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Spot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NewSpot {
            get {
                return ResourceManager.GetString("NewSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no files in this folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoFileInFolderMessage {
            get {
                return ResourceManager.GetString("NoFileInFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no files in this spot.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoFileInSpotMessage {
            get {
                return ResourceManager.GetString("NoFileInSpotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location Acess Consent과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoLocationAcessConsentCaption {
            get {
                return ResourceManager.GetString("NoLocationAcessConsentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At Here requires consent to access location. Please consent it in settings.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoLocationAcessConsentMessage {
            get {
                return ResourceManager.GetString("NoLocationAcessConsentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location Service Off과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoLocationServiceCaption {
            get {
                return ResourceManager.GetString("NoLocationServiceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location serivces are disabled. Please enable it in your system.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoLocationServiceMessage {
            get {
                return ResourceManager.GetString("NoLocationServiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no your spot. Make it yours.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoMySpotMessage {
            get {
                return ResourceManager.GetString("NoMySpotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no near spot. Make it yours.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoNearSpotMessage {
            get {
                return ResourceManager.GetString("NoNearSpotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoPasswordCption {
            get {
                return ResourceManager.GetString("NoPasswordCption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password is blank. Please enter it.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoPasswordMessage {
            get {
                return ResourceManager.GetString("NoPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no selected file to pin. Please go back and select again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoSelectedFileMessage {
            get {
                return ResourceManager.GetString("NoSelectedFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main cloud haven&apos;t been signed in. Please sign in.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NoSignedInMessage {
            get {
                return ResourceManager.GetString("NoSignedInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Null Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NullPasswordCaption {
            get {
                return ResourceManager.GetString("NullPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password can&apos;t be null. Please confirm password.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string NullPasswordMessage {
            get {
                return ResourceManager.GetString("NullPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OneDrive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string OneDrive {
            get {
                return ResourceManager.GetString("OneDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pick과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Pick {
            get {
                return ResourceManager.GetString("Pick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pining Spot...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PiningSpot {
            get {
                return ResourceManager.GetString("PiningSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pirvate Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PrivateMode {
            get {
                return ResourceManager.GetString("PrivateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Private Policy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PrivatePolicy {
            get {
                return ResourceManager.GetString("PrivatePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Profile과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PtcSignOutCaption {
            get {
                return ResourceManager.GetString("PtcSignOutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want sign out? Your setting will be intialized.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PtcSignOutMessage {
            get {
                return ResourceManager.GetString("PtcSignOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refreshing...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Refreshing {
            get {
                return ResourceManager.GetString("Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LeftToRight과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en-US과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default spot name is registered.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SetDefaultSpotNameMessage {
            get {
                return ResourceManager.GetString("SetDefaultSpotNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spot Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SpotName {
            get {
                return ResourceManager.GetString("SpotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   At Here과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StartCaption {
            get {
                return ResourceManager.GetString("StartCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can set other clouds in settings. Enjoy At Here!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Terms of Service과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong Email or Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WrongEmailPasswordCaption {
            get {
                return ResourceManager.GetString("WrongEmailPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The email address or password is wrong. Please confirm your email and password.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WrongEmailPasswordMessage {
            get {
                return ResourceManager.GetString("WrongEmailPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WrongPasswordCaption {
            get {
                return ResourceManager.GetString("WrongPasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password is wrong. Please confirm password.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WrongPasswordMessage {
            get {
                return ResourceManager.GetString("WrongPasswordMessage", resourceCulture);
            }
        }
    }
}
